### ISSUE TITLE
Radio buttons and checkboxes not showing up?

### ISSUE THREAD

**Issue by nathanielevan** [phocus/gtk#12]
With Adwaita theme:
![screenshot](https://user-images.githubusercontent.com/9361126/160529966-c1c4709a-cdaa-40e0-8851-22c6047acdec.png)

With Phocus, installed from source (master branch):
![screenshot-2](https://user-images.githubusercontent.com/9361126/160530001-d669e9e6-b6e9-4637-b505-e072c4a6bd20.png)

**Comment by phisch** [comment]
Just as a confirmation, the `menuitem` elements do actually contain `check` and `radio` elements: 
![image](https://user-images.githubusercontent.com/1282767/160562360-7d9e1a91-4e17-412e-8a44-02a6a9eb1c64.png)

From the properties I checked in the debugger, it makes no sense that they aren't displayed.
I'll figure this out and fix it pretty soon when i'm introducing some more modern changes to phocus.

**Comment by phisch** [comment]
Actually wanted to figure this out right away, turns out check and radio elements were exclusively styled in checkbutton and radiobutton elements. I extracted them, and adjusted their spacing for the menuitem.

It should look as expected now:
![check_radio](https://user-images.githubusercontent.com/1282767/160567298-1fcfef5a-1bea-480e-a3e2-2dd8214ee799.png)

Thanks for the find and report @nathanielevan
